public class ExceptionAll {
//    public void callA(){
//        try{
//        // Exception handling stub !!
//        }catch (Exception e){
//            System.out.println("Exception caught");
//        }
//        System.out.println("Keep on process");
//    }
//
//    public void callB(){
//        try{
//            callC();
//        }catch (Exception e){
//            System.out.println("Exception caught on the behalf of callC");
//        }
//    }
//
//    public void callC() throws Exception{
//        //Exception happening
//    }
//
//    public void call() throws  Exception{
//        //explicit exception creation
//        throw new Exception("Explicit Exception");
//    }
//    public static void main(String[] args) {
//        public void finallyTest(){
//            try{
//                int i = 0;
//                System.out.println("try block");
////              return
//                int j = 10 / i; //ArithmeticException
//            }catch (Exception e){
//                System.out.println("exception block");
//                return;
//            }finally {
//                System.out.println("finally block");
//            }
//            System.out.println("outside of finally");
//        }
//
//    }



}
